### ISSUE TITLE
Interesting deserialize_with example

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/serde-rs.github.io#22]
@locallycompact had this use case:

_assets/test-stratum.morph:_

``` yaml
- repo: http://example.com/repo.git
  ref: aaaaaa
  bit: assets/test-bit.bit
```

_assets/test-bit.bit:_

``` yaml
configureCommands:
- "foodedoo"
buildCommands:
- "ladida"
installCommands:
- "dooopdedoop"
```

One file contains the path to another file. We can use deserialize_with to inline the contents of the second file into a struct representing the first.
