### ISSUE TITLE
Explain that `std` feature is not additive

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/serde-rs.github.io#59]
The features page should recommend having your own `std` feature if you depend on no_std Serde.

```toml
[features]
std = ["serde/std"]
```
